import type { Metadata } from "next";
//Fonts
import { manrope } from "@/Fonts/Fonts";
//i18n
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
//css
import "@/styles/globals.css";
import ThemeProvider from "@/providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const messages = await getMessages();
  return (
    <html
      lang="en"
      className={`${manrope.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider>
            {children}
            </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
